# Generated by Django 4.1 on 2023-06-13 04:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("snippets", "0004_alter_query_number_customtoken"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="query",
            name="query_date",
        ),
        migrations.RemoveField(
            model_name="query",
            name="user",
        ),
        migrations.CreateModel(
            name="Task",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("query_date", models.DateTimeField(auto_now_add=True)),
                ("is_batch", models.BooleanField()),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tasks",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="query",
            name="task",
            field=models.ForeignKey(
                default=0,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="queries",
                to="snippets.task",
            ),
        ),
    ]
