# Generated by Django 4.1 on 2023-06-14 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("snippets", "0006_task_finish_cnt_task_total_cnt"),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="total_cnt",
            field=models.IntegerField(),
        ),
    ]
